"""Add template_id to Event

Revision ID: 03df4fbc7a4a
Revises: 464ec686ccbb
Create Date: 2025-05-06 17:57:35.865814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03df4fbc7a4a'
down_revision = '464ec686ccbb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_event_template_id',
            'event_template',
            ['template_id'],
            ['id']
        )



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
