"""Add team_id and status to VolunteerAvailability

Revision ID: 40883148b9e4
Revises: 6db3afc6f5d4
Create Date: 2025-05-17 14:56:03.459942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40883148b9e4'
down_revision = '6db3afc6f5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(
            'fk_volunteer_availability_team_id',  # ✅ explicit constraint name
            'team',
            ['team_id'],
            ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
