"""Add position to EventSong

Revision ID: c8c71ef4fe24
Revises: 71fc65677cfa
Create Date: 2025-05-18 18:26:15.894114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c71ef4fe24'
down_revision = '71fc65677cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_song', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
