"""Add is_admin flag to Volunteer

Revision ID: 335b70ac6ca8
Revises: 48e04e175e4b
Create Date: 2025-05-17 18:05:58.513597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335b70ac6ca8'
down_revision = '48e04e175e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
