"""Add password_hash column to Volunteer

Revision ID: 48e04e175e4b
Revises: 7e8eac5a94f1
Create Date: 2025-05-17 16:54:35.631651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e04e175e4b'
down_revision = '7e8eac5a94f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
