"""Add availability_locked flag to Event model

Revision ID: 6db3afc6f5d4
Revises: ec0d54854e41
Create Date: 2025-05-16 16:08:10.574216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db3afc6f5d4'
down_revision = 'ec0d54854e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('availability_locked')

    # ### end Alembic commands ###
