"""Add TemplateTeamRole table

Revision ID: 70346993ef1f
Revises: a00bf74caf20
Create Date: 2025-05-10 15:52:14.172968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70346993ef1f'
down_revision = 'a00bf74caf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_team_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['event_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_team_role')
    # ### end Alembic commands ###
