"""Add unique constraint on volunteer/event in VolunteerAvailability

Revision ID: 7e8eac5a94f1
Revises: 40883148b9e4
Create Date: 2025-05-17 15:56:39.697281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8eac5a94f1'
down_revision = '40883148b9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_volunteer_event', ['volunteer_id', 'event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.drop_constraint('uix_volunteer_event', type_='unique')

    # ### end Alembic commands ###
