"""Add template_id to TeamRole

Revision ID: a00bf74caf20
Revises: 03df4fbc7a4a
Create Date: 2025-05-10 15:08:26.913234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00bf74caf20'
down_revision = '03df4fbc7a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        'fk_teamrole_template_id', 
        'event_template',
        ['template_id'],
        ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teamrole_template_id', type_='foreignkey')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
