"""Add Song model

Revision ID: a5ac099ee442
Revises: 335b70ac6ca8
Create Date: 2025-05-18 15:37:57.255176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ac099ee442'
down_revision = '335b70ac6ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('key_male', sa.String(length=20), nullable=True),
    sa.Column('key_female', sa.String(length=20), nullable=True),
    sa.Column('tempo', sa.String(length=50), nullable=True),
    sa.Column('time_signature', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('youtube_link', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
