"""Add is_lead to VolunteerTeamRole

Revision ID: ef611b90564a
Revises: 
Create Date: 2025-05-05 14:19:47.194276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef611b90564a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_team_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lead', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_team_role', schema=None) as batch_op:
        batch_op.drop_column('is_lead')

    # ### end Alembic commands ###
